# Generated by Django 4.2.3 on 2023-07-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicegen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Invoice', 'Invoice'), ('Receipt', 'Receipt')], max_length=50, null=True),
        ),
    ]
